### ISSUE TITLE
aardvark scan asserts if no device is connected

### ISSUE THREAD

**Issue by mwalle** [kontron/python-aardvark#2]
$ aardvark scan
Traceback (most recent call last):
  File "bin/aardvark", line 9, in <module>
    load_entry_point('pyaardvark==0.2.1', 'console_scripts', 'aardvark')()
  File "/home/mwalle/test2/local/lib/python2.7/site-packages/pyaardvark/cli_tool.py", line 147, in main
    args.func(a, args)
  File "/home/mwalle/test2/local/lib/python2.7/site-packages/pyaardvark/cli_tool.py", line 70, in scan
    for port in pyaardvark.find_devices():
  File "/home/mwalle/test2/local/lib/python2.7/site-packages/pyaardvark/aardvark.py", line 63, in find_devices
    assert num_devices > 0
AssertionError

**Comment by Manu3l0us** [comment]
Have the same issue. Seems to be not a good idea to use an assertion there. I would expect an empty list.

**Comment by Manu3l0us** [comment]
Thank you
