### ISSUE TITLE
ImportError on M1 mac

### ISSUE THREAD

**Issue by devangs3** [kontron/python-aardvark#25]
Hi, I tried to run an example code as below `import aardvark_py as a

a.aa_find_devices(1)

handle = a.aa_open(0)

print(a.aa_features(handle))

a.aa_close(handle)`

But I am getting an error as below. Are any dependencies missing/not available for an M1 Mac at the moment? 

/usr/local/bin/python3.10 /Users/devangsinghs/PycharmProjects/pressureSensor/aardvark_test.py
Traceback (most recent call last):
  File "/Users/devangsinghs/PycharmProjects/pressureSensor/aardvark_test.py", line 1, in <module>
    import aardvark_py as a
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aardvark_py/__init__.py", line 93, in <module>
    from . import aardvark as api
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aardvark_py/aardvark/__init__.py", line 17, in <module>
    from .darwin import *
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aardvark_py/aardvark/darwin/__init__.py", line 11, in <module>
    from .arch64 import *
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aardvark_py/aardvark/darwin/arch64/__init__.py", line 9, in <module>
    from .aardvark import *
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aardvark_py/aardvark/darwin/arch64/aardvark.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aardvark_py/aardvark/darwin/arch64/aardvark.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))

Process finished with exit code 1

**Comment by mwalle** [comment]
Could you try the latest master, I've updated the aardvark api to 5.60 but I'm not sure if the aardvark API supports the arm64 macos arch.
